services:
  db:
    image: postgres:16
    restart: always
    shm_size: 128mb

    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase

    ports:
      - 5432:5432

    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
