# services:
#   db:
#     image: postgres:16
#     restart: always
#     shm_size: 128mb

#     environment:
#       POSTGRES_USER: user
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: mydatabase

#     ports:
#       - 5432:5432

#     volumes:
#       - db_data:/var/lib/postgresql/data

# volumes:
#   db_data:

version: '3.8'

services:
  recall-backend:
    image: recall-king-api
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recall-backend
    environment:
      - DB_HOST=recall-postgres
      - DB_PORT=5432
      - DB_USER=youruser
      - DB_PASSWORD=yourpassword
      - DB_NAME=yourdb
    ports:
      - "8080:8080"
    depends_on:
      - recall-postgres
    networks:
      - recall-net

  recall-postgres:
    image: postgres:15
    container_name: recall-postgres
    environment:
      - POSTGRES_USER=youruser
      - POSTGRES_PASSWORD=yourpassword
      - POSTGRES_DB=yourdb
    ports:
      - "5432:5432"
    networks:
      - recall-net

networks:
  recall-net:
    driver: bridge
